"""Generate product themes from the maintained theme registry; no third-party dependencies."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
themes=json.loads((ROOT/'handoff/themes-v4.json').read_text())
assert len({t['id'] for t in themes})==len(themes)==12
assert sum(t['group']=='原始主题' for t in themes)==8
css='/* Generated by tools/build_themes.py; edit handoff/themes-v4.json. */\n'
for t in themes:
 css+='body.theme-'+t['id']+'{'+''.join('--'+k+':'+v+';' for k,v in t['tokens'].items())+'color-scheme:'+t['mode']+';}\n'
(ROOT/'prototype/themes-v4.css').write_text(css)
js='/* Generated by tools/build_themes.py; edit handoff/themes-v4.json. */\nwindow.ThemeCatalog='+json.dumps(themes,ensure_ascii=False,separators=(',',':'))+';\n'
js+='(()=>{D.themes=ThemeCatalog; const priorV4Defaults=D.defaultState.bind(D); D.defaultState=()=>({...priorV4Defaults(),theme:"sunrise",avatarFamily:"original"}); D.version="4.1.0-design";})();\n'
(ROOT/'prototype/themes-v4.js').write_text(js)
print('Generated 8 original themes and 4 separate historical candidates')
