/* Local domain tests. No browser, network, or user data. Run: node tools/record_loop_contract.mjs <site-root> */
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=path.resolve(process.argv[2]||'.');
const element={textContent:'',hidden:true,classList:{toggle(){}},focus(){},setAttribute(){},scrollIntoView(){}};
const sandbox={window:{},document:{getElementById:()=>element,querySelector:()=>element},URLSearchParams,Date,Math,App:{unsavedDraft:false},UI:{esc:String,button:()=>'',link:()=>'',icon:()=>''}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'prototype/data.js'),'utf8'),sandbox);sandbox.D=sandbox.window.D;
vm.runInContext(fs.readFileSync(path.join(root,'prototype/flows-v2.js'),'utf8'),sandbox);const V2=sandbox.window.V2;sandbox.V2=V2;
let state=sandbox.D.defaultState(),route='topic-workspace?topic=work-choice',failure=false,formCallback,dialogTitle='',passes=0;
const clone=x=>JSON.parse(JSON.stringify(x));
V2.bind({get state(){return state;},current:()=>route,commit(fn){if(failure)return false;const next=clone(state);fn(next);state=next;return true;},nav(r,p={}){route=r+(Object.keys(p).length?'?'+new URLSearchParams(p):'');},toast(){},status(){},close(){},show(title){dialogTitle=title;},repaint(){},form(title,label,value,fn){formCallback=fn;},addSource(){}});
const dispatch=(a,ds={})=>V2.dispatch(a,{dataset:ds});
const field=(key,value)=>V2.input({target:{dataset:{input:'topic-field',field:key},value}});
const test=(name,fn)=>{fn();passes++;console.log('PASS',name);};
const save=()=>dispatch('topic-save',{topic:'work-choice',id:new URLSearchParams(route.split('?')[1]).get('id')||''});
test('original topic schemas remain intact',()=>{assert.equal(V2.schemas['work-choice'].length,4);assert.equal(Object.keys(V2.schemas).length,5);assert.equal(V2.topicFields('work-choice').length,7);});
test('empty record is not manufactured',()=>{save();assert.equal(state.observations.length,0);});
test('draft-only failed commit retains text',()=>{failure=true;field('issue','先整理再讨论，还是先讨论再动手？');save();assert.equal(state.observations.length,0);assert.match(V2.getDraft(V2.topicKey('work-choice')).issue,/先整理/);assert.equal(V2.hasUnsaved,true);failure=false;});
test('record saved locally without account or assessment',()=>{field('options','先整理；先讨论');field('evidence','昨天准备两个要点后表达更清楚，这是我的观察。');field('unknown','是否只是因为话题更熟悉？');save();assert.equal(state.observations.length,1);assert.equal(state.observations[0].revision,1);assert.equal(state.logged,false);assert.equal(state.sessions.length,0);assert.equal(V2.hasUnsaved,false);});
const noteId=state.observations[0].id;
test('explicit action stores original saved revision',()=>{dispatch('add-action');assert.equal(formCallback('下次先写两个要点，观察是否更容易开始'),true);assert.equal(state.actions[0].sourceId,noteId);assert.equal(state.actions[0].sourceVersion,'1');assert.equal(state.actions[0].sourceSnapshot.version,'1');});
const actionId=state.actions[0].id,firstText=state.actions[0].text,originalSource=clone(state.actions[0].sourceSnapshot);
test('review stores its own plan snapshot',()=>{dispatch('action-outcome',{id:actionId,outcome:'partial'});V2.input({target:{dataset:{input:'action-review'},value:'只列出了一点，愿意再观察'}});dispatch('save-action-review',{id:actionId});assert.equal(state.actions[0].reviews.length,1);assert.equal(state.actions[0].reviews[0].actionText,firstText);assert.equal(state.actions[0].reviews[0].actionRevision,1);});
test('changing plan never rewrites previous review',()=>{dispatch('edit-action',{id:actionId});formCallback('先确认问题，再写一点');assert.equal(state.actions[0].revision,2);assert.equal(state.actions[0].reviews[0].actionText,firstText);});
test('editing note keeps ID, previous revision and action source',()=>{route='topic-workspace?topic=work-choice&id='+noteId;field('issue','第二次整理：加上交流对象这个条件');save();assert.equal(state.observations[0].id,noteId);assert.equal(state.observations[0].revision,2);assert.equal(state.observations[0].revisions[0].revision,1);assert.match(state.observations[0].revisions[0].fields.issue,/先整理/);assert.deepEqual(state.actions[0].sourceSnapshot,originalSource);});
test('dirty draft cannot silently become assistant source',()=>{field('issue','未正式保存的改写');dispatch('topic-to-assistant',{id:noteId});assert.equal(dialogTitle,'先选择采用哪个版本');assert.equal(state.assistantSources.length,0);dispatch('topic-attach-saved',{id:noteId});assert.equal(state.assistantSources[0].version,'2');assert.match(state.assistantSources[0].excerpt,/第二次整理/);assert.doesNotMatch(state.assistantSources[0].excerpt,/未正式保存/);assert.equal(state.conversations.length,0);});
test('same source ID with newer revision is not deduplicated to old action',()=>{route='topic-workspace?topic=work-choice&id='+noteId;dispatch('topic-action-saved',{id:noteId});formCallback(firstText);assert.equal(state.actions.length,2);assert.equal(state.actions[1].sourceVersion,'2');});
test('new and legacy state normalize without invented snapshots',()=>{const n=V2.normalize(clone(state));assert.equal(n.observations[0].revisions.length,1);const old=clone(state);delete old.observations[0].revisions;delete old.actions[0].sourceSnapshot;delete old.actions[0].sourceVersion;V2.normalize(old);assert.equal(old.actions[0].sourceSnapshot,undefined);});
test('corrupt nested histories and sources are rejected',()=>{for(const change of [s=>s.observations[0].revisions={},s=>s.observations[0].revisions=[{revision:1,fields:{},text:5}],s=>s.actions[0].sourceSnapshot={title:'x'},s=>s.actions[0].reviews=[{id:'bad',actionRevision:0}]]){const bad=clone(state);change(bad);assert.throws(()=>V2.normalize(bad));}});
test('export excludes note snapshot without mutating local action',()=>{const exported=V2.actionsForExport(state.actions,false);assert.equal(exported[0].sourceSnapshot,undefined);assert.equal(exported[0].sourceUnavailable,'excluded-from-export');assert.deepEqual(state.actions[0].sourceSnapshot,originalSource);assert.equal(exported[0].reviews[0].actionText,firstText);});
test('source deletion clears full snapshot but keeps plan and reviews',()=>{const cleaned=V2.omitSourceText(state.actions[0],'deleted');assert.equal(cleaned.sourceSnapshot,undefined);assert.equal(cleaned.sourceUnavailable,'deleted');assert.equal(cleaned.sourceVersion,'1');assert.equal(cleaned.reviews[0].actionText,firstText);});
console.log(JSON.stringify({passed:passes,failed:0,scope:'Pure local V2 record/action/review contract; no browser verification'}));
