/* V2 task-oriented screens. Existing secondary routes remain reachable through Views.map. */
(() => {
  'use strict';
  const {esc,icon,mark,button:B,link:L,top,row,bottleGrid,composer,empty}=UI;
  const section=(title,extra='')=>`<div class="section-head"><h2>${title}</h2>${extra}</div>`;
  const saveState=()=>`<p class="editor-save" id="editor-save-state" role="status">${V2.draftStatus}</p>`;
  const date=x=>x?new Date(x).toLocaleDateString('zh-CN',{month:'short',day:'numeric'}):'本机记录';
  const oldConversation=Views.map.conversation;
  const pending=s=>s.actions.find(a=>a.status==='active');
  function taskCard(a){return `<section class="current-action"><span class="eyebrow">接着上次 · 我的尝试</span><h2>${esc(a.text)}</h2><p>可以记录有帮助、没变化，或还没尝试。</p>${L('看看这次发生了什么','action-detail',{cls:'btn full',after:'arrow','data-id':a.id})}</section>`;}
  function home(s){
    const active=s.sessions.find(x=>x.id===s.activeSession),unfinished=active?.status==='in-progress',done=active?.status==='completed',a=pending(s);
    let task;
    if(unfinished){task=`<span class="eyebrow">上次停在这里</span><div class="row between"><h2>继续这次答题</h2><span class="count-label">${Object.keys(active.answers).length}<small> / 3</small></span></div><p class="task-desc">已保存的答案还在，无需重新开始。</p><div class="resume-progress"><span style="width:${Object.keys(active.answers).length/3*100}%"></span></div>${B('继续第 '+(active.index+1)+' 题','resume',{cls:'btn full',after:'arrow'})}<div class="task-foot">${L('查看已答','review',{cls:'textbtn','data-id':active.id})}<span>同一份答卷 · 原版本</span></div>`;}
    else if(a){task=`<span class="eyebrow">接着上次 · 我的尝试</span><h2 class="action-title">${esc(a.text)}</h2><p class="task-desc">如实记录这次的情况，暂时没做也可以。</p>${L('记下这次的观察','action-detail',{cls:'btn full',after:'arrow','data-id':a.id})}<div class="task-foot">${L('全部小尝试','actions',{cls:'textbtn'})}<span>不催打卡</span></div>`;}
    else if(done){task=`<span class="eyebrow">体验已完成</span><h2>答案已留下，理解慢慢来</h2><p class="task-desc">回看自己当时的选择，或了解一份报告怎样阅读。</p>${L('回看这次作答','review',{cls:'btn full',after:'arrow','data-id':active.id})}<div class="task-foot">${L('查看独立报告样例','report',{cls:'textbtn','data-id':D.report.id})}${B('再体验一次','start-new',{cls:'textbtn'})}</div>`;}
    else{task=`<span class="eyebrow">从性格探索开始</span><div class="row between"><h2>16PF 性格探索</h2><span class="entry-symbol">${icon('bottle')}</span></div><p class="task-desc">了解倾向，也看看哪些情境会让自己不同。</p><div class="version-row"><span class="version-current">原版方向</span>${B('AI 重置版 · 待开放','mode',{cls:'version-future','data-id':'ai',icon:'lock'})}</div>${B('体验 3 道示例题','start',{cls:'btn full',after:'arrow'})}<div class="task-foot"><span>约 1 分钟 · 仅体验交互</span>${L('先看报告','report',{cls:'textbtn','data-id':D.report.id})}</div>`;}
    return `<div class="topline brandline"><div class="wordmark">${mark()}<strong>见己</strong><span class="edition-label">体验原型</span></div>${L('','appearance',{cls:'iconbtn',icon:'palette','aria-label':'主题与形象'})}</div>
      <header class="welcome-v2"><div><span class="eyebrow">${unfinished||a||done?'欢迎回来':'给自己一点时间'}</span><h1>${unfinished||a?'从上次的地方，<br>继续了解自己。':'看懂自己的倾向，<br>也找到下一小步。'}</h1></div><div class="avatar-scene"><img src="assets/person-${s.avatar}.svg" alt="手拿笔记本的人物插画">${L('','appearance',{cls:'avatar-change',icon:'edit','aria-label':'更换形象'})}</div></header>
      <section class="primary-task">${task}</section>
      <p class="quiet-boundary">${icon('info','sm')}示例题不计分。正式题源与常模尚未接入。</p>
      ${unfinished&&a?`<button class="resume-note" data-action="nav" data-route="action-detail" data-id="${a.id}">${icon('flag')}<span class="grow"><strong>也有一件小尝试等你回看</strong><small>${esc(a.text)}</small></span>${icon('chevron','sm')}</button>`:''}
      ${section('从生活里认识自己',L('全部探索','explore',{cls:'textbtn',after:'arrow'}))}
      <div class="start-pair"><button data-action="nav" data-route="topic" data-id="work-choice"><span class="tile-symbol green">${icon('explore')}</span><strong>工作怎么选</strong><small>把期待和约束摆清楚</small></button><button data-action="nav" data-route="topic" data-id="relationships"><span class="tile-symbol peach">${icon('chat')}</span><strong>需要怎么说</strong><small>从一件具体的事开始</small></button></div>
      ${section('先留下一点真实的自己')}${row('记下今天的一刻','不用答题，也能开始积累','journal','edit')}
      <details class="more-exploration"><summary>更多认识自己的方式</summary><div class="plain-list">${row('每日轻探索','题组待就绪，当前可留一句观察','','sun','',{action:'daily'})}${row('了解一个因子','16 个角度，未知处保留留白','','bottle','',{action:'all-factors'})}${row('假设实验','调整示意位置，不写入个人画像','simulation','explore')}${row('高低不代表优劣','关于阅读结果的方法','article','book','',{'data-id':'read-traits'})}</div></details>`;
  }
  function explore(s){
    const text=s.exploreSearch.trim().toLowerCase();const filtered=D.topics.filter(t=>(s.exploreCategory==='全部'||t.category===s.exploreCategory)&&(!text||[t.title,t.desc,t.category].join(' ').toLowerCase().includes(text)));
    return `<div class="topline"><span class="eyebrow">探索 · 从真实问题出发</span>${B('收藏','favorites',{cls:'textbtn',icon:'bookmark'})}</div><h1>最近，<br>想理清哪件事？</h1><p class="page-lead">先整理自己的情况，再决定下一步。</p>
      <div class="search-box"><label class="sr-only" for="explore-search">搜索探索主题</label>${icon('search')}<input id="explore-search" data-input="explore-search" value="${esc(s.exploreSearch)}" placeholder="搜索工作、相处、学习…" autocomplete="off">${B('','clear-search',{cls:'search-clear',icon:s.exploreSearch?'close':'filter','aria-label':s.exploreSearch?'清空搜索':'筛选说明'})}</div>
      <div class="chips" aria-label="探索类别">${['全部','工作','相处','学习','生活'].map(c=>B(c,'category',{cls:s.exploreCategory===c?'active':'','data-id':c,'aria-pressed':s.exploreCategory===c})).join('')}</div>
      <div class="browse-info"><span>${filtered.length} 个整理方向</span><span>自己填写 · 不作匹配打分</span></div>
      ${filtered.length?filtered.map((t,i)=>`<button class="topic-v2 ${i===0?'featured':''} ${t.color}" data-action="nav" data-route="topic" data-id="${t.id}"><div class="topic-copy"><span class="eyebrow">${t.category} · ${V2.schemas[t.id].length} 个整理问题</span><h2>${t.title}</h2><p>${t.desc}</p><span class="topic-output">${t.id==='work-choice'?'留下一份选择清单':t.id==='relationships'?'留下一句具体表达':t.id==='city-choice'?'留下一份条件清单':t.id==='learning'?'留下一次学习实验':'留下一条情境观察'} ${icon('arrow','sm')}</span></div><img src="assets/${t.art}.svg" alt="" loading="lazy"></button>`).join(''):empty('没有找到这个方向','可以换个关键词，或清空筛选。',B('清空筛选','clear-filters',{cls:'btn secondary'}))}`;
  }
  function topic(s,p){
    const t=D.topics.find(x=>x.id===p.id);if(!t)return `<h1>主题暂不可用</h1>${L('回到探索','explore')}`;
    const note=s.observations.find(x=>x.topicId===t.id);
    return `${top('探索',B('','favorite',{cls:'iconbtn',icon:'bookmark','data-id':t.id,'aria-label':s.favorites.includes(t.id)?'取消收藏':'收藏这个主题','aria-pressed':s.favorites.includes(t.id)}))}<div class="topic-detail-hero ${t.color}"><span class="eyebrow">${t.category} · 自助整理</span><h1>${t.title}</h1><p>${t.desc}</p><img src="assets/${t.art}.svg" alt=""></div><div class="topic-facts"><span>${V2.schemas[t.id].length} 个问题</span><span>可跳过、可暂停</span><span>不计分</span></div>
      ${section('这次可以留下什么')}<p class="body-copy">${t.output.replace('，而不是','，不提供')}</p><ol class="compact-steps">${V2.schemas[t.id].map(x=>`<li><strong>${x[1]}</strong><span>${x[2]}</span></li>`).join('')}</ol>
      ${B('开始整理我的情况','topic-journal',{cls:'btn full','data-id':t.id,after:'arrow'})}${note?L('打开上次的整理','topic-workspace',{cls:'btn secondary full space-12','data-topic':t.id,'data-id':note.id}):''}<p class="quiet-boundary">内容为本轮原创整理框架；不预测职业、关系或城市选择结果。</p>`;
  }
  function topicWorkspace(s,p){
    const t=D.topics.find(x=>x.id===p.topic);if(!t)return `<h1>未找到这个主题</h1>${L('回到探索','explore')}`;
    const found=s.observations.find(x=>x.id===p.id&&x.topicId===t.id);if(p.id&&!found)return `<h1>原记录暂不可用</h1>${L('回到记录','records')}`;
    const d=V2.getDraft(V2.topicKey(t.id,p.id),found?.fields||{});
    return `${top('返回')}<span class="eyebrow">${t.short} · ${found?'本人记录':'整理进行中'}</span><h1 class="info-title">把自己的情况，<br>摆清楚一点。</h1><p class="page-lead">空着的地方可以以后再补，不必一次写完。</p>${found?'<div class="saved-banner">'+icon('check','sm')+' 已正式保存到记录 · 可继续修改</div>':''}<div class="topic-form">${V2.schemas[t.id].map(([key,label,placeholder],i)=>`<section><label class="field-label" for="topic-${key}"><span class="step-no">${String(i+1).padStart(2,'0')}</span>${label}</label><textarea id="topic-${key}" class="textarea" data-input="topic-field" data-field="${key}" maxlength="1500" placeholder="${esc(placeholder)}">${esc(d[key]||'')}</textarea></section>`).join('')}</div>${saveState()}${B(found?'保存这次修改':'保存这份整理','topic-save',{cls:'btn full space-16','data-topic':t.id,'data-id':found?.id||'',after:'check'})}
      ${found?`<section class="next-step-panel"><span class="eyebrow">接下来，选一个就好</span><h2>理解之后，试一小步</h2>${B('留下一个小尝试','add-action',{cls:'btn tonal full',icon:'flag'})}${B('带着这份记录问助理','topic-to-assistant',{cls:'textbtn full','data-id':found.id,icon:'chat'})}</section>`:''}<p class="quiet-boundary">本机记录；发送给助理前仍需你明确确认。</p>`;
  }
  function report(s,p){
    if(p.id&&p.id!==D.report.id)return `<h1>这份报告暂不可用</h1>${L('回到记录','records')}`;
    const work=s.reportContext!=='relationship',src=D.reportSource(work?'work':'relationship');
    return `${top('返回',B('','nav',{cls:'iconbtn',icon:'share','data-route':'share','aria-label':'选择分享范围','data-id':D.report.id}))}
      <div class="report-identity">${icon('book','sm')} 独立报告样例 · 虚构人物小林</div>
      <header class="report-title-v2"><span class="eyebrow">阅读一个人的情境，而非接受一个标签</span><h1>${work?'准备充分时，<br>表达更从容。':'熟悉的关系里，<br>慢慢打开自己。'}</h1><p>以下展示阅读方式，与刚才的三道示例题无关。</p></header>
      <nav class="report-chapters" aria-label="报告目录">${[['report-overview','要点'],['report-evidence','依据'],['report-personal','我的观察'],['report-action','下一步']].map(([id,name])=>B(name,'report-jump',{cls:'','data-id':id})).join('')}</nav>
      <section id="report-overview" class="report-block" tabindex="-1"><div class="context-switch" aria-label="阅读情境"><button class="${work?'active':''}" data-action="report-context" data-id="work" aria-pressed="${work}">工作</button><button class="${!work?'active':''}" data-action="report-context" data-id="relationship" aria-pressed="${!work}">相处</button></div><h2>先读三个要点</h2><div class="key-takeaways"><div><span>01</span><p><strong>${work?'可能有帮助':'在什么情境里'}</strong>${work?'有时间梳理要点时，更容易把理由说明白。':'和熟悉的人一起时，更愿意认真回应。'}</p></div><div><span>02</span><p><strong>可能有代价</strong>${work?'等到完全想好再说，可能错过一些参与机会。':'在陌生场合等待太久，别人可能不知道他想参与。'}</p></div><div><span>03</span><p><strong>值得进一步观察</strong>${work?'准备时间、话题熟悉度和参与人数，各有什么影响？':'人员熟悉度、话题与当日状态，各有什么影响？'}</p></div></div></section>
      <section id="report-evidence" class="report-block" tabindex="-1"><div class="row between"><h2>这些说法从哪里来</h2><span class="source-type">样例情境</span></div><blockquote class="quote"><span class="caption">小林 · 虚构生活片段</span>${src.excerpt}</blockquote><p class="body-copy">${work?'一次表达的表现有多种可能解释。这里仅呈现可继续观察的条件，不能从片段推导出人格分数。':'安静和愿意靠近别人可以同时存在。单次聚会中的表现不能代表所有关系。'}</p>${B('核对来源与版本','source-report',{cls:'source-row',icon:'link',after:'chevron'})}<details class="factor-detail" open><summary><span>16 个因子角度</span><small>位置示意 · B、O 留白</small></summary><p class="small muted">水位仅为独立示意。更满不代表更好，暂无依据不显示为零。</p>${bottleGrid()}</details></section>
      <section id="report-personal" class="report-block" tabindex="-1"><span class="source-type own">本人观察 · 与样例分开</span><h2 class="space-12">你的经历，有哪里不同？</h2><p class="body-copy">写具体的情境，也可以直接质疑这段解释。</p><label class="field-label space-16" for="report-note">我自己的真实经历</label><textarea id="report-note" class="textarea" data-input="report-note" maxlength="1500" placeholder="例如：在熟悉的小组里，我不太需要准备就能说清楚。">${esc(V2.getDraft('report:'+s.reportContext,''))}</textarea>${saveState()}${B('保存本人观察','save-report-note',{cls:'btn secondary full space-12',icon:'edit'})}${s.reportNotes.length?L('查看已保存的本人观察','records',{cls:'textbtn full'}):''}</section>
      <section id="report-action" class="report-block" tabindex="-1"><div class="next-step-panel"><span class="eyebrow">下次，试一个小变化</span><h2>${work?'先留一点准备时间':'从一个具体细节加入'}</h2><p>${work?'下次临时被问到时，可以说：“给我一点整理时间，我从两点说起。”':'下次想加入对话时，可以先回应对方说的一个具体细节。'}</p>${B('留下这个小尝试','add-action',{cls:'btn full',icon:'flag','data-context':work?'work':'relationship'})}<small>你可以修改。保存只建立尝试，不建立性格结论。</small></div>${B('带着样例情境问助理','quote-report',{cls:'btn secondary full space-16',icon:'chat'})}</section>
      <details class="report-boundary"><summary>样例范围与正式测量的区别</summary><p>情境、瓶中位置均为虚构材料。正式题源、计分、常模与解释尚未接入。因子名称是界面工作译名。用户写下的观察独立保存，不能倒推或修改正式分数。</p></details>`;
  }
  function assistant(s){
    const hasSample=s.assistantSources.some(x=>x.kind==='sample-report');
    return `<div class="topline"><span class="eyebrow">个人助理 · 先整理，再判断</span>${B(s.logged?`剩余 ${Math.max(0,10-s.used)} / 10`:'登录后每日 10 次','quota',{cls:'quota-pill',icon:'info'})}</div><header class="assistant-v2"><div class="assistant-dot">${icon('chat')}</div><h1>从一件具体的事，<br>开始聊。</h1><p>可以带上自己的记录，也可以只说眼前的问题。</p></header>
      <div class="assistant-seeds">${B('我想理清一件事','prompt',{cls:'seed','data-id':'recent',icon:'leaf'})}${B('带上一份记录','context',{cls:'seed',icon:'book'})}</div>
      ${hasSample?'<div class="source-warning">'+icon('info','sm')+' 本次含虚构样例；它不会成为你的个人记忆。</div>':''}${composer(s.assistantDraft,s.assistantSources,s.logged)}
      <div class="data-boundary"><span>${icon('link','sm')}只用本次选中资料</span><span>${icon('memory','sm')}记忆需另行确认</span></div><p class="demo-caption">当前回复为预写演示，不联网，也不提供真实智能分析。</p>
      ${section('接着上次聊',L('全部','conversations',{cls:'textbtn',after:'arrow'}))}${s.conversations.length?s.conversations.slice(-3).reverse().map(c=>`<button class="history-row" data-action="nav" data-route="conversation" data-id="${c.id}">${icon('chat')}<span class="grow"><h3>${esc(c.title)}</h3><small>${c.messages.length} 条消息 · 本机对话</small></span>${icon('chevron','sm')}</button>`).join(''):'<div class="empty-inline">还没有对话。你写下的草稿会保留，登录不会自动发送。</div>'}<div class="plain-list space-24">${row('助理记住了什么','随时查看来源、修改或停用','memories','memory')}</div>`;
  }
  function me(s){
    const notes=[...s.observations,...s.reportNotes].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')),a=pending(s);
    return `<div class="topline"><span class="eyebrow">我的 · 本机空间</span>${L('','settings',{cls:'iconbtn',icon:'settings','aria-label':'打开设置'})}</div><header class="profile-v2"><div class="profile-avatar"><img src="assets/person-${s.avatar}.svg" alt="我的插画形象"></div><div class="grow"><h1>${esc(s.name)}</h1><p>留下经历，慢慢形成自己的认识。</p></div>${B('','edit-name',{cls:'iconbtn',icon:'edit','aria-label':'修改称呼'})}</header>
      <section class="personal-start"><span class="eyebrow">${notes.length?'最近留下的自己':'从第一条真实经历开始'}</span><h2>${notes.length?esc(notes[0].title):'值得留下的，是具体的时刻。'}</h2><p>${notes.length?esc(notes[0].text.slice(0,88)):'今天哪一刻，你对自己多了一点了解？一句话也可以。'}</p>${L(notes.length?'打开这条记录':'记下一个自己的时刻',notes[0]?.kind==='topic-record'?'topic-workspace':'journal',{cls:'btn full',icon:'edit',...(notes.length?{'data-id':notes[0].id,...(notes[0].kind==='topic-record'?{'data-topic':notes[0].topicId}:{})}:{})})}</section>
      ${a?`<button class="resume-note" data-action="nav" data-route="action-detail" data-id="${a.id}">${icon('flag')}<span class="grow"><strong>一件小尝试，还可以回看</strong><small>${esc(a.text)}</small></span>${icon('chevron','sm')}</button>`:''}
      <div class="personal-links">${row('我的记录',notes.length?`${notes.length} 条本人记录 · 体验答卷单独标识`:'观察、专题整理与体验答卷','records','book')}${row('我的小尝试',s.actions.length?`${s.actions.length} 件尝试 · 不要求连续打卡`:'计划、实际结果与后续观察','actions','flag')}${row('正在认识的自己','查看各条认识的来源与留白','portrait','explore')}</div>
      ${section('资料由自己掌握')}<div class="plain-list">${row('助理记忆','确认、纠正和停用','memories','memory')}${row('数据与隐私','导出本机资料；引用与留存分开控制','data','shield')}${row('引用与留存设置','聊天保存与长期记忆独立控制','privacy','lock')}</div>
      ${section('账号与服务')}<div class="plain-list">${row(s.logged?'演示账号':'登录 / 注册说明',s.logged?'未连接真实认证服务':'本机记录不依赖登录',s.logged?'account':'auth','user')}${row('会员与使用次数','查看规则、方案与原订单','membership','crown')}${row('主题与形象',D.themes.find(t=>t.id===s.theme).name,'appearance','palette')}</div>`;
  }
  function journal(s,p){
    const found=s.observations.find(x=>x.id===p.id)||s.reportNotes.find(x=>x.id===p.id);
    if(p.id&&!found)return `<h1>这条记录暂不可用</h1>${L('回到记录','records')}`;
    if(found?.kind==='topic-record')return `${top('记录')}<h1>${esc(found.title)}</h1><p class="page-lead">这份记录包含分项整理，可按原结构继续修改。</p>${L('打开原整理','topic-workspace',{cls:'btn full space-24','data-topic':found.topicId,'data-id':found.id})}`;
    const title=found?.title||(p.kind==='daily'?'给今天留一句话':'一个自己的时刻');
    return `${top('返回')}<span class="source-type own">本人观察</span><h1 class="info-title">${esc(title)}</h1><p class="page-lead">发生了什么？你当时怎么想？也可以只写一句。</p><label class="field-label space-24" for="journal-text">我的记录</label><textarea id="journal-text" class="textarea long-editor" data-input="journal" maxlength="4000" placeholder="那一刻，我…">${esc(V2.getDraft(V2.journalKey(p),found?.text||''))}</textarea>${saveState()}${B(found?'保存修改':'保存这个时刻','save-journal',{cls:'btn full space-24','data-id':p.id||'','data-title':title,after:'check'})}<p class="quiet-boundary">草稿和正式记录分开保存。不会自动交给助理或建立记忆。</p>${found?B('删除这条记录','delete-journal',{cls:'textbtn full space-12','data-id':found.id}):''}`;
  }
  function actions(s){
    const groups=[['active','还在尝试'],['reviewed','已经留过观察'],['cancelled','暂时放下']];
    return `${top('我的',B('新建','new-action',{cls:'btn tonal compact',icon:'plus'}))}<span class="eyebrow">理解 → 尝试 → 观察</span><h1 class="info-title">小尝试，<br>按自己的节奏来。</h1><p class="page-lead">没尝试、没变化、不适合，都可以如实留下。</p>${s.actions.length?groups.map(([status,label])=>{const items=s.actions.filter(a=>(a.status==='done'?'reviewed':a.status)===status);return items.length?`${section(label)}${items.map(a=>`<button class="action-list-item" data-action="nav" data-route="action-detail" data-id="${a.id}"><span class="action-icon">${icon(status==='active'?'flag':'book')}</span><span class="grow"><strong>${esc(a.text)}</strong><small>${a.reviews?.length?`${a.reviews.length} 次观察 · `:''}${a.sourceKind==='sample-report'?'来自样例的自选尝试':'本人选择的尝试'}</small></span>${icon('chevron','sm')}</button>`).join('')}`:'';}).join(''):empty('还没有小尝试','挑一件小到可以开始的事，之后看看实际发生了什么。',B('写一个小尝试','new-action',{cls:'btn tonal compact'}))}<div class="plain-list space-24">${row('只记观察，不安排事情','观察可以独立存在','journal','edit')}</div>`;
  }
  function actionDetail(s,p){
    const a=s.actions.find(x=>x.id===p.id);if(!a)return `<h1>这个小尝试暂不可用</h1>${L('回到小尝试','actions')}`;
    const d=V2.getDraft(V2.actionKey(a.id),{}),reviews=a.reviews||[];
    return `${top('返回',B('修改','edit-action',{cls:'textbtn','data-id':a.id,icon:'edit'}))}<span class="eyebrow">${a.status==='active'?'我的尝试':a.status==='cancelled'?'暂时放下':'已经留过观察'}</span><h1 class="action-detail-title">${esc(a.text)}</h1><div class="provenance-line">${icon('link','sm')}${a.sourceKind==='sample-report'?'灵感来自报告样例 · 由你选择保存':'本人保存的小尝试'}${a.sourceId?' · 保留原来源':''}</div>
      <section class="review-form"><h2>这次，实际发生了什么？</h2><div class="outcome-choices" role="group" aria-label="尝试的实际结果">${V2.outcomes.map(([value,label])=>B(label,'action-outcome',{cls:d.outcome===value?'selected':'','data-id':a.id,'data-outcome':value,'aria-pressed':d.outcome===value})).join('')}</div><label class="field-label space-24" for="action-observation">有什么具体观察？ <small>选填</small></label><textarea id="action-observation" class="textarea" data-input="action-review" maxlength="2000" placeholder="例如：准备了两点后，更容易开口；但被追问时还需要时间。">${esc(d.text||'')}</textarea>${saveState()}${B('保存这次观察','save-action-review',{cls:'btn full space-16','data-id':a.id,after:'check'})}</section>
      <div class="row wrap space-12">${a.status==='active'?B('这次先放下','cancel-action',{cls:'textbtn','data-id':a.id}):B('重新放回当前尝试','restart-action',{cls:'textbtn','data-id':a.id})}${L('全部小尝试','actions',{cls:'textbtn'})}</div>
      ${reviews.length?`${section('以前的观察')}<div class="observation-timeline">${reviews.slice().reverse().map(r=>`<article><span class="timeline-dot"></span><div class="row between"><strong>${esc(V2.outcomes.find(x=>x[0]===r.outcome)?.[1]||r.outcome)}</strong><time>${date(r.createdAt)}</time></div><p>${esc(r.text||'这次只记录了实际结果，没有补充文字。')}</p></article>`).join('')}</div>`:''}<p class="quiet-boundary">观察与计划分开保存。系统不根据文字自动判断你是否完成。</p>`;
  }
  function records(s){
    let items=[...s.observations.map(x=>({...x,type:'本人观察',route:x.kind==='topic-record'?'topic-workspace':'journal'})),...s.reportNotes.map(x=>({...x,type:'报告补充',route:'journal'})),...s.sessions.map(x=>({...x,type:x.status==='completed'?'体验答卷':'未完成',title:'3 道交互示例题',text:x.status==='completed'?'只读答卷，不产生个人分数':`已保存 ${Object.keys(x.answers).length} / 3 题`,route:x.status==='completed'?'review':'question'}))];
    if(s.recordFilter==='本人记录')items=items.filter(x=>['本人观察','报告补充'].includes(x.type));else if(s.recordFilter==='全部答卷')items=items.filter(x=>['体验答卷','未完成'].includes(x.type));else if(s.recordFilter!=='全部')items=items.filter(x=>x.type===s.recordFilter);items.sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));
    return `${top('我的',L('写观察','journal',{cls:'btn tonal compact',icon:'plus'}))}<h1 class="info-title">回到当时，<br>看看自己怎么想。</h1><p class="page-lead">本人经历与示例答卷各有标识，不合成成长分。</p><div class="chips">${['全部','本人记录','全部答卷','本人观察','报告补充','未完成','体验答卷'].map(x=>B(x,'record-filter',{cls:s.recordFilter===x?'active':'','data-id':x,'aria-pressed':s.recordFilter===x})).join('')}</div>${items.length?items.map(x=>`<button class="record-item" data-action="nav" data-route="${x.route}" data-id="${x.id}" ${x.topicId?'data-topic="'+x.topicId+'"':''}><span class="pill outline">${x.kind==='topic-record'?'专题整理':x.type}</span><h3>${esc(x.title)}</h3><p class="summary">${esc(x.text)}</p><div class="foot"><span>${date(x.createdAt)} · 本机</span>${icon('arrow','sm')}</div></button>`).join(''):empty('这里还没有这类记录','先留下真实经历，之后可以找回、修改或删除。',L('写一个观察','journal',{cls:'btn secondary'}))}<div class="plain-list space-24">${row('查看我的小尝试','计划与实际结果','actions','flag')}${row('两份结果的可比性','核对来源和量纲后再比较','compare','book')}</div>`;
  }
  Object.assign(Views.map,{home,explore,topic,'topic-workspace':topicWorkspace,report,assistant,me,journal,actions,'action-detail':actionDetail,records});
  Views.map.conversation=(s,p)=>{let html=oldConversation(s,p);const c=s.conversations.find(x=>x.id===p.id);if(c?.interrupted)html=html.replace('<div class="chat-label">','<div class="hint error" role="status">上次演示在窗口关闭时中断，未自动重发。原问题仍在。</div><div class="chat-label">');return html;};
})();
